### ISSUE TITLE
🌱: Sign Up Page

### ISSUE THREAD

**Issue by dibi-dibi-dib** [dibi-dibi-dib/create-login-logic#2]
## **Task Description:**
- [x] 회원가입 양식 페이지를 만들어야 합니다. 
- [x] 사용자에게 필요한 정보를 입력받을 수 있는 양식을 제공하고, 올바른 형식의 데이터가 입력되었는지 확인할 수 있어야 합니다.

<br>

## **Skills Required:**
- [x]  React 컴포넌트와 React Hooks를 사용하여 폼 요소 만들기
- [x]  useState 훅을 활용하여 상태(state) 관리하기
- [x]  useEffect 훅을 사용하여 양식의 유효성 검사와 같은 부수 효과 처리하기
- [x]  CSS 스타일링 적용하기
- [x]  Axios를 사용하여 POST 요청을 보내고, 서버로부터의 응답에 따라 성공 또는 실패 시 처리하기

<br>

## **Resources:**
[Example Sign up Page: Mailchimp](https://login.mailchimp.com/signup) <br>
![image](https://github.com/dibi-dibi-dib/create-login-logic/assets/156323554/d063ef44-209c-48cd-9c60-823e6422f39ax?width=300px)

[Example Sign up Page: MDN](https://accounts.firefox.com/oauth/?response_type=code&client_id=720bc80adfa6988d&state=zAk_AdrAqa7Wi3c_qgPYUg&redirect_uri=https%3A%2F%2Fdeveloper.mozilla.org%2Fusers%2Ffxa%2Flogin%2Fcallback%2F&scope=openid%2Bopenid%2Bprofile%2Bemail%2Bprofile%3Asubscriptions&access_type=offline&nonce=_jDnUGAVQy0_YHh5QG1lFg)
![image](https://github.com/dibi-dibi-dib/create-login-logic/assets/156323554/3db289fe-8a36-40d2-8548-4be53a04d2d0)
