### ISSUE TITLE
🌱: Login Page

### ISSUE THREAD

**Issue by dibi-dibi-dib** [dibi-dibi-dib/create-login-logic#3]
## **Task Description:**
- [x] 로그인 페이지 형식으로 변환 및 업데이트해야 합니다.
- [x] 사용자에게 필요한 정보를 입력받을 수 있는 로그인 폼을 제공하고, 올바른 형식의 데이터가 입력되었는지 확인할 수 있어야 합니다.

<br>

## **Skills Required:**
- [x] `React` 컴포넌트와 `React Hooks`를 사용하여 폼 요소 만들기
- [x] `useState` 훅을 활용하여 상태(`state`) 관리하기
- [x] `useEffect` 훅을 사용하여 폼의 유효성 검사와 같은 부수 효과 처리하기
- [x] `CSS` 스타일링 적용하기
- [x] `Axios`를 사용하여 `POST` 요청을 보내고, 서버로부터의 응답에 따라 성공 또는 실패 시 처리하기

<br>

## **Resources:**
[Dropbox](https://www.dropbox.com/login)

![image](https://github.com/dibi-dibi-dib/create-login-logic/assets/156323554/c514ece3-8bd4-4b25-b8aa-cbf8095c5a39)

[Webflow](https://webflow.com/dashboard/login)
![image](https://github.com/dibi-dibi-dib/create-login-logic/assets/156323554/37ce2d8e-5a9a-48d8-b7e3-39a683033517)
